apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd-devops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://7D9E2FE5D80408CD05E1AAB698FC3D77.gr7.us-east-1.eks.amazonaws.com
    namespace: argocd-devops
  project: default
  source:
    chart: prometheus
    helm:
      values: |
        pushgateway:
          enabled: false
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 15.6.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
