apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: guestbook
spec: 
  destination: 
    namespace: argocd-devops
    server: https://7D9E2FE5D80408CD05E1AAB698FC3D77.gr7.us-east-1.eks.amazonaws.com
  project: default
  source:
    path: charts/guestbook
    repoURL: https://github.com/xeroxpro/argocd.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
