apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: guestbook
  namespace: argocd-devops
spec: 
  destination: 
    namespace: argocd-devops
    server: "server: https://7D9E2FE5D80408CD05E1AAB698FC3D77.gr7.us-east-1.eks.amazonaws.com"
  project: default
  source:
    helm:
     version: v3 
    path: charts/guestbook
    repoURL: "https://github.com/xeroxpro/argocd"
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
