---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-subchart
  namespace: devops-argocd
spec:
  destination:
    namespace: devops-argocd
    server: https://kubernetes.default.svc
  project: charts
  source:
    path: quarkus-subchart/
    repoURL: http://ec2-54-209-222-75.compute-1.amazonaws.com:8080/gitlab-instance-a3df9ff3/charts.git
    targetRevision: HEAD
  sync:
    comparedTo:
      destination:
        namespace: devops-argocd
        server: https://kubernetes.default.svc
      source:
        path: quarkus-subchart/
        repoURL: http://ec2-54-209-222-75.compute-1.amazonaws.com:8080/gitlab-instance-a3df9ff3/charts.git
        targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
