apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://7D9E2FE5D80408CD05E1AAB698FC3D77.gr7.us-east-1.eks.amazonaws.com
    namespace: argocd-devops
  project: default
  source:
    path: apps/
    repoURL: "git@github.com:xeroxpro/argocd.git"
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

